---
title: "Zooplankton sample inventory package based on Minimal EDI package generated using EMLassemblyline and ediutilities"
author: "Joe Futrelle, Stace Beaulieu, Kate Morkeski"
date: "r Sys.Date()"
output: html_notebook
---

Libraries used

```{r}
# two of the required packages are installed from GitHub
# library(remotes)
# remotes::install_github("EDIorg/EMLassemblyline")
# remotes::install_github("WHOIGit/ediutilities")

library(EMLassemblyline)
library(ediutilities)
library(here)
library(lubridate)
library(dplyr)
```

Read data tables

```{r}

meta <- read.csv(here('nes-lter-zooplankton-tow-metadata-v2-input.csv'))
meta$datetime_UTC_start <- dmy_hms(paste(meta$date_start_UTC, meta$time_start_UTC))
meta$datetime_UTC_end <- dmy_hms(paste(meta$date_end_UTC, meta$time_end_UTC))

#put cruises in chronological order
meta <- meta[order(meta$datetime_UTC_start),]
#save this order, then order rows by cruise and cast
meta_cruises <- unique(meta$cruise)
meta <- meta[with(meta, order(match(cruise, meta_cruises), cast)),]

meta <- meta |> 
  relocate(datetime_UTC_start, .after = sample_name) |>
  relocate(datetime_UTC_end, .before = lat_start) |>
  select(-date_start_UTC, -time_start_UTC, -date_end_UTC, -time_end_UTC) |>
  rename(event = sample_name) |>
  rename(decimalLatitudeStart = lat_start) |>
  rename(decimalLongitudeStart = lon_start) |>
  rename(decimalLatitudeEnd= lat_end) |>
  rename(decimalLongitudeEnd = lon_end) |>
  rename(net_max_depth = net_max_depth_m) |>
  rename(max_wire_out = max_wire_out_m) |>
  rename(wire_rate_out = wire_rate_out_m_min) |>
  rename(wire_rate_in = wire_rate_in_m_min) |>
  rename(vol_filtered_335 = vol_filtered_m3_335)|>
  rename(vol_filtered_150 = vol_filtered_m3_150) |>
  mutate(net_max_depth = round(net_max_depth, 2)) |>
  mutate(across(c(vol_filtered_335, vol_filtered_150, haul_factor_10m2_335, haul_factor_10m2_150, haul_factor_100m3_335, haul_factor_100m3_150), \(x) round(x, 3)))

write.csv(meta, 'nes-lter-zooplankton-tow-metadata-v2.csv', row.names=FALSE)

```

```{r}

inventory <- read.csv(here('nes-lter-zooplankton-transect-inventory-v2-input.csv'))

#set case of cruise column
inventory$cruise <- toupper(inventory$cruise)

# check for any differences in cruise ID between inventory and meta
inv_cruises <- unique(inventory$cruise)
setdiff(inv_cruises, meta_cruises)

#match metadata table order of cruises and casts
inventory <- inventory[with(inventory, order(match(cruise, meta_cruises), cast)),]

write.csv(inventory, 'nes-lter-zooplankton-transect-inventory-v2.csv', row.names=FALSE)

```
Check for discrepancies between casts in the two tables

```{r}

meta$cruisecast <- paste0(meta$cruise, "-", meta$cast)
inventory$cruisecast <- paste0(inventory$cruise, "-", inventory$cast)
setdiff(meta$cruisecast, inventory$cruisecast)
#is.element("EN644-9", meta$cruisecast) #TRUE
#is.element("EN644-9", inventory$cruisecast) #FALSE
#v2: four casts are in metadata table and not in inventory (no sample collected)

```

Read the Excel metadata template and generate text templates used by
EMLassemblyline

```{r}
# Alex provided metadata in csv files, so use below write.table steps instead of excel_to_template
#excel_to_template(here('NES-LTER_Transect_Sample_Inventory'), 'nes-lter-zooplankton', rights='CC0', file_type=".md")

write.table(read.csv("nes-lter-zooplankton-tow-metadata-v2-column-headers.csv", sep=","), "attributes_nes-lter-zooplankton-tow-metadata-v2.txt", quote = FALSE, na="", sep="\t", row.names = FALSE)

write.table(read.csv("nes-lter-zooplankton-transect-inventory-v2-column-headers.csv", sep=","), "attributes_nes-lter-zooplankton-transect-inventory-v2.txt", quote = FALSE, na="", sep="\t", row.names = FALSE)

write.table(read.csv("nes-lter-zooplankton-transect-inventory-v2-categoricalVariablesHeaders.csv", sep=","), "catvars_nes-lter-zooplankton-transect-inventory-v2.txt", quote = FALSE, na="", sep="\t", row.names = FALSE)

write.table(read.csv("nes-lter-zooplankton-tow-metadata-v2-categoricalVariablesHeaders.csv", sep=","), "catvars_nes-lter-zooplankton-tow-metadata-v2.txt", quote = FALSE, na="", sep="\t", row.names = FALSE)

write.table(read.csv("personnel.csv", sep=","), "personnel.txt", quote = FALSE, na="", sep="\t", row.names = FALSE)

template_core_metadata(path = here(), license = 'CC0', file.type = ".md")

```

Generate the package and insert the parent project node into the resulting EML

```{r}

temp_coverage <- temporal_coverage(meta$datetime_UTC_start)

# use package ID assigned in vortex README
pkg_id <- 'knb-lter-nes.24.2'

make_eml(path = here(),
         dataset.title ='Zooplankton sample inventory for Northeast U.S. Shelf Long Term Ecological Research (NES-LTER) Transect cruises, ongoing since 2018',
         data.table = c('nes-lter-zooplankton-transect-inventory-v2.csv', 'nes-lter-zooplankton-tow-metadata-v2.csv'),
         #data.table = c('inventory.csv', 'meta.csv'),
         data.table.description = c('Zooplankton sample inventory for NES-LTER Transect cruises', 'Zooplankton tow metadata for NES-LTER Transect cruises'),
         data.table.name = c('nes-lter-zooplankton-transect-inventory', 'nes-lter-zooplankton-tow-metadata'),
         data.table.quote.character = c('"','"'),
         temporal.coverage = temp_coverage,
         geographic.description = "NES-LTER Transect",
         geographic.coordinates = geographic_coordinates(meta$decimalLatitudeStart, meta$decimalLongitudeStart), # Not including end-of-tow coordinates
         maintenance.description = "ongoing",
         user.id = "NES",
         user.domain = "LTER",
         package.id = pkg_id)

project_insert(pkg_id,'parent_project_NESI-II_RAPID_OOI.txt')
```
